import express from "express"
import { createServer } from "node:http"
import { join, dirname, resolve, sep } from "node:path"
import { fileURLToPath } from "node:url"
import fs from "node:fs"
import { load } from "cheerio"
import { server as wisp } from "@mercuryworkshop/wisp-js/server"

import { proxies, transports, supports, get_compatibility, resolve_backend, mounts_for, packages_for } from "./registry.js"
import { check_packages, find_package } from "./pkgs.js"
import { LithiumError } from "./errors.js"
import { run_doctor } from "./doctor.js"
import { color, set_color } from "./color.js"

export { proxies, transports, supports, get_compatibility, LithiumError, run_doctor }

const __dirname = dirname(fileURLToPath(import.meta.url))

// generated service worker for custom proxies (built-ins use client/sw.js)
const sw_source = (custom) => `// generated by lithium for the "${custom.name}" proxy
self.addEventListener("install", () => self.skipWaiting())
self.addEventListener("activate", (event) => event.waitUntil(self.clients.claim()))
${custom.serviceWorker}
`

// main function
//   proxy                 "ultraviolet" | "scramjet" | anything you registered
//   transport             "epoxy" | "libcurl" | anything you registered
//   staticDir, port       your frontend folder / the port to listen on
//   crossOriginIsolation  send COOP/COEP (only for proxies that want it)
//   middleware            [(req, res, next) => ...] runs before Lithium's routes
//   wisp                  options for the wisp server, e.g. { allow_loopback_ips: true }
//                         (wisp is one shared instance, so this is process-wide)
//   strict                false: warn about version problems instead of throwing
//   quiet                 no startup log line
export function create_lithium_server(opts = {}) {
  const static_dir = opts.staticDir || "public"
  const port = opts.port || 8080
  const proxy = opts.proxy || "ultraviolet"
  const transport = opts.transport || "epoxy"
  const isolation = opts.crossOriginIsolation !== false
  const strict = opts.strict !== false
  const quiet = opts.quiet === true
  if (opts.color != null) set_color(Boolean(opts.color))

  const middleware = opts.middleware ?? []
  if (!Array.isArray(middleware) || middleware.some((m) => typeof m !== "function")) {
    throw new LithiumError("INVALID_OPTION", "middleware must be an array of (req, res, next) functions", { option: "middleware" })
  }
  if (opts.wisp != null && (typeof opts.wisp !== "object" || Array.isArray(opts.wisp))) {
    throw new LithiumError("INVALID_OPTION", "wisp must be an object of wisp-js server options", { option: "wisp" })
  }

  // Throws UNKNOWN_PROXY / UNKNOWN_TRANSPORT / INCOMPATIBLE_TRANSPORT
  const backend = resolve_backend(proxy, transport)

  // Wrong package generations "sort of work" and then die on random sites,
  // so catch them at startup with an error that says what to do.
  const findings = check_packages(packages_for(backend))
  const bad = findings.filter((f) => f.level === "error")
  if (bad.length) {
    if (strict) {
      const { message, hint, ...details } = bad[0]
      throw new LithiumError(bad[0].code, hint ? `${message} (${hint})` : message, { ...details, all: bad })
    }
    for (const f of bad) console.warn(color.yellow(`[lithium] ${f.message}`))
  }
  for (const f of findings.filter((x) => x.level === "warn")) if (!quiet) console.warn(color.yellow(`[lithium] ${f.message}`))

  if (opts.wisp) Object.assign(wisp.options, opts.wisp)

  // absolute or relative, resolve() handles both (and Windows drive letters)
  const static_path = resolve(process.cwd(), static_dir)
  const client_path = join(__dirname, "..", "client")

  const app = express()
  const server = createServer(app)

  for (const fn of middleware) app.use(fn)

  // COOP/COEP make the page cross-origin isolated. Scramjet needs it (it
  // passes the isolation on to every proxied site); Ultraviolet doesn't want it.
  const isolated = Boolean(backend.proxy.isolation && isolation)
  if (isolated) {
    app.use((_req, res, next) => {
      res.setHeader("Cross-Origin-Opener-Policy", "same-origin")
      res.setHeader("Cross-Origin-Embedder-Policy", "require-corp")
      next()
    })
  }

  app.use("/client/", express.static(client_path))

  // sw.js has to be served from the root so its scope covers the whole site.
  // The client registers it as /sw.js?proxy=<name>; built-in proxies get the
  // shared client/sw.js, custom ones a generated worker.
  const custom_sw = backend.proxy.builtin ? null : sw_source(backend.proxy)
  app.get("/sw.js", (_req, res) => {
    res.setHeader("Service-Worker-Allowed", "/")
    if (custom_sw) res.type("js").send(custom_sw)
    else res.sendFile(join(client_path, "sw.js"))
  })

  // routes first (e.g. generated uv.config.js), so they win over static files
  backend.proxy.routes?.(app)

  // static folders. A missing file is reported once, here, instead of
  // turning into a mystery 404 in the browser later.
  const problems = []
  let mounts
  try {
    mounts = mounts_for(backend)
  } catch (err) {
    throw new LithiumError("FILES_MISSING", `couldn't locate the files for ${proxy} + ${transport}: ${err.message}`, {
      proxy, transport, cause: String(err?.message ?? err), hint: "run `npx lithium doctor`",
    })
  }
  for (const m of mounts) {
    app.use(m.url, express.static(m.dir))
    for (const f of m.files) {
      if (!fs.existsSync(join(m.dir, f))) {
        problems.push({ code: "FILES_MISSING", label: m.label, file: f, dir: m.dir })
        console.error(color.red(`[lithium] ${m.label}: expected "${f}" in ${m.dir} but it isn't there`))
      }
    }
  }

  // --- config injection ------------------------------------------------------
  // The client reads window.__LITHIUM_CONFIG__ to know which proxy/transport
  // the server was started with.
  const impl = backend.impl
  const injected = {
    proxy,
    transport,
    interface: backend.interface,
    transportUrl: impl.mount + (impl.entry ?? "index.mjs"),
    ...(backend.proxy.builtin ? {} : { clientModule: backend.proxy.clientModule }),
    isolated,
  }
  const config_script = "window.__LITHIUM_CONFIG__=" + JSON.stringify(injected).replace(/</g, "\\u003c") + ";"

  function inject_config(html) {
    try {
      const $ = load(html)
      const tag = `<script>${config_script}</script>`
      if ($("head").length) $("head").prepend(tag)
      else if ($("body").length) $("body").prepend(tag)
      else return tag + html
      return $.html()
    } catch (err) {
      console.error("[lithium] cheerio injection failed:", err)
      return html
    }
  }

  // map a request path to an .html file inside static_path, or null.
  // Never returns anything outside static_path (no ../ tricks).
  function html_file_for(req_path) {
    let rel
    try {
      rel = decodeURIComponent(req_path)
    } catch {
      return null
    }
    if (rel.endsWith("/")) rel += "index.html"
    if (!rel.endsWith(".html")) return null

    const full = resolve(static_path, "." + rel)
    if (full !== static_path && !full.startsWith(static_path + sep)) return null
    try {
      return fs.statSync(full).isFile() ? full : null
    } catch {
      return null
    }
  }

  // parsing HTML on every request is wasteful, so cache by mtime
  const html_cache = new Map()
  function read_html(file) {
    const mtime = fs.statSync(file).mtimeMs
    const hit = html_cache.get(file)
    if (hit && hit.mtime === mtime) return hit.html
    const html = inject_config(fs.readFileSync(file, "utf8"))
    html_cache.set(file, { mtime, html })
    return html
  }

  app.use((req, res, next) => {
    if (req.method !== "GET") return next()
    const file = html_file_for(req.path)
    if (!file) return next()
    try {
      return res.type("html").send(read_html(file))
    } catch (err) {
      console.error("[lithium] failed to read/inject file:", err)
      next()
    }
  })

  // everything else in the static dir (js, css, images, ...)
  app.use(express.static(static_path))

  // nothing in static dir matched "/" -> show that we're alive
  app.get("/", (_req, res) => {
    res.json({ msg: "lithium server running", proxy, transport, staticDir: static_path })
  })

  // wisp lives at /wisp/ and nowhere else
  server.on("upgrade", (req, sock, head) => {
    let pathname = null
    try {
      pathname = new URL(req.url ?? "/", "http://localhost").pathname
    } catch {}

    if (pathname === "/wisp/" && req.headers.upgrade?.toLowerCase() === "websocket") {
      req.url = pathname
      wisp.routeRequest(req, sock, head)
    } else if (server.listenerCount("upgrade") === 1) {
      // only close it if nobody else (e.g. your own ws handler) is listening
      sock.destroy()
    }
  })

  const info = {
    proxy,
    transport,
    interface: backend.interface,
    isolation: isolated,
    packages: packages_for(backend).map((p) => ({ name: p.name, version: find_package(p.name)?.version ?? null })),
    problems,
  }
  if (!quiet) {
    const pkgs = info.packages.map((p) => `${p.name}@${color.dim(p.version ?? "?")}`).join(", ")
    console.log(color.green(`[lithium] ${proxy} + ${transport}`) + color.dim(` (${backend.interface} interface${isolated ? ", cross-origin isolated" : ""}): `) + pkgs)
  }

  return { app, server, port, backend: info }
}
